# Generated by Django 4.0.3 on 2022-05-16 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('card_board', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cardinfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('price', models.CharField(max_length=200)),
                ('enddata', models.CharField(max_length=200)),
                ('picture', models.CharField(max_length=200)),
                ('oldlink', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Jamescardinfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('price', models.CharField(max_length=200)),
                ('enddata', models.CharField(max_length=200)),
                ('picture', models.CharField(max_length=200)),
                ('oldlink', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Jordanscardinfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('price', models.CharField(max_length=200)),
                ('enddata', models.CharField(max_length=200)),
                ('picture', models.CharField(max_length=200)),
                ('oldlink', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Kobecardinfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('price', models.CharField(max_length=200)),
                ('enddata', models.CharField(max_length=200)),
                ('picture', models.CharField(max_length=200)),
                ('oldlink', models.CharField(max_length=500)),
            ],
        ),
    ]
